-- ============================= ELIMINADO DEL ESQUEMA DE LA BASE DE DATOS ====================
-- ===================================== TABLES (41) ===============================
DROP TABLE acomodo;

DROP TABLE material_master;

DROP TABLE avion_sistema_entretenimiento;

DROP TABLE proveedor_estacion;

DROP TABLE avion_capacidad;

DROP TABLE relacion_flota;

DROP TABLE equipamiento_comisariato;

DROP TABLE perfil_usuario;

DROP TABLE avion_audifono;

DROP TABLE horario;

DROP TABLE vuelo;

DROP TABLE matriz_detalle;

DROP TABLE contacto_proveedor_estacion;

DROP TABLE codigo_servicio;

DROP TABLE empleado;

DROP TABLE grafico_detalle;

DROP TABLE modulo_perfil;

DROP TABLE traduccion;

DROP TABLE matriz;

DROP TABLE area;

DROP TABLE acomodo_detalle;

DROP TABLE grafico;

DROP TABLE sistema_entretenimiento;

DROP TABLE proveedor;

DROP TABLE perfil;

DROP TABLE tipo_proveedor;

DROP TABLE clase;

DROP TABLE usuario;

DROP TABLE material;

DROP TABLE avion;

DROP TABLE kit_master;

DROP TABLE categoria_material;

DROP TABLE producto;

DROP TABLE estacion;

DROP TABLE ciudad;

DROP TABLE pais;

DROP TABLE region;

DROP TABLE tipo_equipo_avion;

DROP TABLE modelo_avion;

DROP TABLE compania;

DROP TABLE parametros;

