-- ============================= ELIMINADO DEL ESQUEMA DE LA BASE DE DATOS ====================
     [java] =>dropOrder: after :{contacto_proveedor_estacion=2040000,
     [java] 	 equipamiento_comisariato=1030100,
     [java] 	 proveedor_estacion=1030100,
     [java] 	 avion=1030000,
     [java] 	 estacion=1020000,
     [java] 	 vuelo=60101,
     [java] 	 empleado=40101,
     [java] 	 avion_audifono=40100,
     [java] 	 material_master=30200,
     [java] 	 avion_sistema_entretenimiento=30100,
     [java] 	 avion_capacidad=30100,
     [java] 	 modulo_perfil=20101,
     [java] 	 modulo=10101,
     [java] 	 tipo_equipo_avion=10100,
     [java] 	 ciudad=10100,
     [java] 	 master=4,
     [java] 	 material=3,
     [java] 	 modelo_avion=3,
     [java] 	 perfil_usuario=2,
     [java] 	 proveedor=1,
     [java] 	 horario=1,
     [java] 	 pais=1,
     [java] 	 codigo_servicio=1,
     [java] 	 region=0,
     [java] 	 compania=0,
     [java] 	 tipo_proveedor=0,
     [java] 	 traduccion=0,
     [java] 	 parametros=0,
     [java] 	 categoria_material=0,
     [java] 	 relacion_flota=0,
     [java] 	 usuario=0,
     [java] 	 sistema_entretenimiento=0,
     [java] 	 clase=0,
     [java] 	 area=0,
     [java] 	 perfil=0}

-- ===================================== TABLES (35) ===============================
DROP TABLE contacto_proveedor_estacion;

DROP TABLE equipamiento_comisariato;

DROP TABLE proveedor_estacion;

DROP TABLE avion;

DROP TABLE estacion;

DROP TABLE vuelo;

DROP TABLE empleado;

DROP TABLE avion_audifono;

DROP TABLE material_master;

DROP TABLE avion_sistema_entretenimiento;

DROP TABLE avion_capacidad;

DROP TABLE modulo_perfil;

DROP TABLE modulo;

DROP TABLE tipo_equipo_avion;

DROP TABLE ciudad;

DROP TABLE master;

DROP TABLE material;

DROP TABLE modelo_avion;

DROP TABLE perfil_usuario;

DROP TABLE proveedor;

DROP TABLE horario;

DROP TABLE pais;

DROP TABLE codigo_servicio;

DROP TABLE region;

DROP TABLE compania;

DROP TABLE tipo_proveedor;

DROP TABLE traduccion;

DROP TABLE parametros;

DROP TABLE categoria_material;

DROP TABLE relacion_flota;

DROP TABLE usuario;

DROP TABLE sistema_entretenimiento;

DROP TABLE clase;

DROP TABLE area;

DROP TABLE perfil;

