-- ============================= ELIMINADO DEL ESQUEMA DE LA BASE DE DATOS ====================
-- ===================================== TABLES (35) ===============================
DROP TABLE contacto_proveedor_estacion;

DROP TABLE material_master;

DROP TABLE equipamiento_comisariato;

DROP TABLE proveedor_estacion;

DROP TABLE vuelo;

DROP TABLE empleado;

DROP TABLE avion_audifono;

DROP TABLE avion_sistema_entretenimiento;

DROP TABLE avion_capacidad;

DROP TABLE modulo_perfil;

DROP TABLE avion;

DROP TABLE modulo;

DROP TABLE estacion;

DROP TABLE tipo_equipo_avion;

DROP TABLE ciudad;

DROP TABLE master;

DROP TABLE material;

DROP TABLE modelo_avion;

DROP TABLE perfil_usuario;

DROP TABLE proveedor;

DROP TABLE horario;

DROP TABLE pais;

DROP TABLE codigo_servicio;

DROP TABLE region;

DROP TABLE compania;

DROP TABLE tipo_proveedor;

DROP TABLE traduccion;

DROP TABLE parametros;

DROP TABLE categoria_material;

DROP TABLE relacion_flota;

DROP TABLE usuario;

DROP TABLE sistema_entretenimiento;

DROP TABLE clase;

DROP TABLE area;

DROP TABLE perfil;

